# Generated by Django 3.0.6 on 2020-06-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorReg',
            fields=[
                ('docname', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('docno', models.CharField(max_length=10)),
                ('clinic', models.CharField(max_length=30)),
                ('docspe', models.CharField(max_length=20)),
                ('docemail', models.CharField(max_length=20)),
                ('docpassword', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='RecepRegister',
            fields=[
                ('recepname', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('recepno', models.CharField(max_length=10)),
                ('recepclinic', models.CharField(max_length=50)),
                ('recepemail', models.CharField(max_length=50)),
                ('receppasswd', models.CharField(max_length=15)),
            ],
        ),
    ]
